version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: fx-exchange-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: fx-exchange-redis
    restart: always
    ports:
      - '${REDIS_PORT}:6379'
